### ISSUE TITLE
Provide a fallback for screenreaders/non-visual browsers

### ISSUE THREAD

**Issue by Primigenus** [Q42/logo#26]
In the header of the Q-site, I want to put the new logo:

```
<div class="logo"><a href="/">
  <q42></q42>
</a></div>
```

This is not accessible because the link has no text.

If I put "Q42" between the opening and closing tags, the text is just rendered as-is. I could hide it with the `overflow:hidden; text-indent: -9000px` trick, but since this is a custom element that we have control over, we should probably provide a better hook for it.

**Comment by marcelduin** [comment]
Fixed in https://github.com/Q42/logo/commit/e336940613242be27487b2c19fc1e4744983cbff

Default auto-adding attributes:
`<q42 title="Q42" role="logo" aria-role="image" aria-label="Q42 Logo">`
