### ISSUE TITLE
Logo script is niet beschikbaar via HTTPS

### ISSUE THREAD

**Issue by mac-cain13** [Q42/logo#45]
Ik wil het logo graag op een site includen die enkel beschikbaar is over https, alleen de logo site geeft een insecure connection error als ik het javascriptje via https probeer te includen. Kunnen we dit fixen?

Als we dat gedaan hebben moet de script-tag in de instructie denk ik ook protocol-loos maken zodat die vanzelf meeswitcht van protocol. Of zitten hier andere nadelen aan die ik niet ken?

**Comment by Primigenus** [comment]
It looks like it should be possible to serve logo.q42.com over HTTPS using CloudFlare by following this guide: https://developer.ubuntu.com/en/blog/2016/02/17/how-host-your-static-site-https-github-pages-and-cloudflare/

**Comment by lukasvan3l** [comment]
how about hosting the logo in https://www.q42.com/q42.js ?

**Comment by lukasvan3l** [comment]
ah, apparantly it's already hosted here: https://storage.googleapis.com/static.q42.nl/q42.js

nice, that file can separately be deployed and doesn't rely on the entire q42.com website. Good solution. I think the todo is to add this link to the README. If people want to use SSL, then use this file.
